/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CityRouteRouteImport } from './routes/city/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityIndexRouteImport } from './routes/city/index'
import { Route as CityCityIdRouteImport } from './routes/city/$cityId'
import { Route as CityCreateIndexRouteImport } from './routes/city/create/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'

const CityRouteRoute = CityRouteRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityIndexRoute = CityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CityRouteRoute,
} as any)
const CityCityIdRoute = CityCityIdRouteImport.update({
  id: '/$cityId',
  path: '/$cityId',
  getParentRoute: () => CityRouteRoute,
} as any)
const CityCreateIndexRoute = CityCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => CityRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/city': typeof CityRouteRouteWithChildren
  '/city/$cityId': typeof CityCityIdRoute
  '/city/': typeof CityIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/city/create/': typeof CityCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/city/$cityId': typeof CityCityIdRoute
  '/city': typeof CityIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/city/create': typeof CityCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/city': typeof CityRouteRouteWithChildren
  '/city/$cityId': typeof CityCityIdRoute
  '/city/': typeof CityIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/city/create/': typeof CityCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/city'
    | '/city/$cityId'
    | '/city/'
    | '/auth/login/'
    | '/auth/signup/'
    | '/city/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/city/$cityId'
    | '/city'
    | '/auth/login'
    | '/auth/signup'
    | '/city/create'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/city'
    | '/city/$cityId'
    | '/city/'
    | '/auth/login/'
    | '/auth/signup/'
    | '/city/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CityRouteRoute: typeof CityRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/city': {
      id: '/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof CityRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/': {
      id: '/city/'
      path: '/'
      fullPath: '/city/'
      preLoaderRoute: typeof CityIndexRouteImport
      parentRoute: typeof CityRouteRoute
    }
    '/city/$cityId': {
      id: '/city/$cityId'
      path: '/$cityId'
      fullPath: '/city/$cityId'
      preLoaderRoute: typeof CityCityIdRouteImport
      parentRoute: typeof CityRouteRoute
    }
    '/city/create/': {
      id: '/city/create/'
      path: '/create'
      fullPath: '/city/create/'
      preLoaderRoute: typeof CityCreateIndexRouteImport
      parentRoute: typeof CityRouteRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CityRouteRouteChildren {
  CityCityIdRoute: typeof CityCityIdRoute
  CityIndexRoute: typeof CityIndexRoute
  CityCreateIndexRoute: typeof CityCreateIndexRoute
}

const CityRouteRouteChildren: CityRouteRouteChildren = {
  CityCityIdRoute: CityCityIdRoute,
  CityIndexRoute: CityIndexRoute,
  CityCreateIndexRoute: CityCreateIndexRoute,
}

const CityRouteRouteWithChildren = CityRouteRoute._addFileChildren(
  CityRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CityRouteRoute: CityRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
