export const cityListData = {
  data: {
    content: [
      {
        id: 13,
        name: "Ahmedabad",
        cityCode: "AMD",
        countryCode: "IN",
        countryName: "India",
        timeZoneOffset: "+05:30",
      },
      {
        id: 8,
        name: "Bengaluru",
        cityCode: "BLR",
        countryCode: "IN",
        countryName: "India",
        timeZoneOffset: "+05:30",
      },
      {
        id: 9,
        name: "Chennai",
        cityCode: "MAA",
        countryCode: "IN",
        countryName: "India",
        timeZoneOffset: "+05:30",
      },
      {
        id: 18,
        name: "Dubai",
        cityCode: "DXB",
        countryCode: "AE",
        countryName: "United Arab Emirates",
        timeZoneOffset: "+04:00",
      },
      {
        id: 11,
        name: "Hyderabad",
        cityCode: "HYD",
        countryCode: "IN",
        countryName: "India",
        timeZoneOffset: "+05:30",
      },
      {
        id: 14,
        name: "Jaipur",
        cityCode: "JAI",
        countryCode: "IN",
        countryName: "India",
        timeZoneOffset: "+05:30",
      },
      {
        id: 10,
        name: "Kolkata",
        cityCode: "CCU",
        countryCode: "IN",
        countryName: "India",
        timeZoneOffset: "+05:30",
      },
      {
        id: 17,
        name: "London",
        cityCode: "LON",
        countryCode: "GB",
        countryName: "United Kingdom",
        timeZoneOffset: "+00:00",
      },
      {
        id: 15,
        name: "Lucknow",
        cityCode: "LKO",
        countryCode: "IN",
        countryName: "India",
        timeZoneOffset: "+05:30",
      },
      {
        id: 7,
        name: "Mumbai",
        cityCode: "BOM",
        countryCode: "IN",
        countryName: "India",
        timeZoneOffset: "+05:30",
      },
      {
        id: 1,
        name: "New Delhi",
        cityCode: "DEL",
        countryCode: "IN",
        countryName: "India",
        timeZoneOffset: "+05:30",
      },
      {
        id: 16,
        name: "New York",
        cityCode: "NYC",
        countryCode: "US",
        countryName: "United States",
        timeZoneOffset: "-05:00",
      },
      {
        id: 12,
        name: "Pune",
        cityCode: "PNQ",
        countryCode: "IN",
        countryName: "India",
        timeZoneOffset: "+05:30",
      },
      {
        id: 19,
        name: "Singapore",
        cityCode: "SIN",
        countryCode: "SG",
        countryName: "Singapore",
        timeZoneOffset: "+08:00",
      },
      {
        id: 20,
        name: "Tokyo",
        cityCode: "TYO",
        countryCode: "JP",
        countryName: "Japan",
        timeZoneOffset: "+09:00",
      },
    ],
    pageNumber: 0,
    pageSize: 20,
    totalElements: 15,
    totalPages: 1,
    first: true,
    last: true,
  },
  error: null,
  message: null,
  status: "success",
  statusCode: 200,
  timestamp: 1784211372212,
};

export const countryListData = {
  data: [
    {
      countryCode: "IN",
      countryName: "India",
    },
    {
      countryCode: "AE",
      countryName: "United Arab Emirates",
    },
    {
      countryCode: "GB",
      countryName: "United Kingdom",
    },
    {
      countryCode: "US",
      countryName: "United States",
    },
    {
      countryCode: "SG",
      countryName: "Singapore",
    },
    {
      countryCode: "JP",
      countryName: "Japan",
    },
  ],
  error: null,
  message: null,
  status: "success",
  statusCode: 200,
  timestamp: 1784211372212,
};
