CREATE SCHEMA IF NOT EXISTS airline;

CREATE TABLE IF NOT EXISTS airline.city
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    city_code    VARCHAR(10)  NOT NULL UNIQUE,
    country_code VARCHAR(5)   NOT NULL,
    country_name VARCHAR(100) NOT NULL,
    region_code  VARCHAR(10),
    time_zone_id VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS airline.airport (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         iata_code VARCHAR(3) NOT NULL UNIQUE,
                         name VARCHAR(255) NOT NULL,
                         time_zone_id VARCHAR(50),
                         location VARCHAR(255),
                         postal_code VARCHAR(20),
                         city_id BIGINT NOT NULL,
                         latitude DOUBLE PRECISION NOT NULL,
                         longitude DOUBLE PRECISION NOT NULL,
                         CONSTRAINT fk_airport_city FOREIGN KEY (city_id) REFERENCES airline.city (id)
);